# Generated by Django 5.2 on 2025-04-19 16:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0002_categoria_fornecedor_produto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrada",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="entrada",
            name="estoque",
        ),
        migrations.AddField(
            model_name="produto",
            name="estoque",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="estoque.estoque",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="visto_por_ultimo",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
