# Generated by Django 5.2 on 2025-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0003_remove_entrada_categoria_remove_entrada_estoque_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="validade",
            field=models.DateField(blank=True, null=True),
        ),
    ]
