# Generated by Django 5.2 on 2025-04-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0004_produto_validade"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entradas_unidade",
                to="estoque.produto",
            ),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entradas_produto",
                to="estoque.produto",
            ),
        ),
    ]
