# Generated by Django 5.2 on 2025-04-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0005_entrada_unidade_alter_entrada_produto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entrada",
            old_name="unidade",
            new_name="unidade_entrada",
        ),
    ]
